name: Laravel Forge Deployment

on:
  workflow_call:

jobs:  
  deployment: 
    runs-on: ubuntu-latest
    env:
      DEPLOY_STAGE_URL: ${{ secrets.FORGE_DEPLOY_STAGING }}
      DEPLOY_PROD_URL: ${{ secrets.FORGE_DEPLOY_PRODUCTION }}
    if: github.ref == 'refs/heads/stage' || github.ref == 'refs/heads/master'
    steps:
      - name: Debug
        run: echo env.DEPLOY_STAGE_URL
      - name: Debug2
        run: echo env.DEPLOY_PROD_URL
      - name: Deploy app staging server
        if: env.DEPLOY_STAGE_URL != '' && github.ref == 'refs/heads/stage'
        uses: fjogeleit/http-request-action@master
        with:
            url: ${{ env.DEPLOY_STAGE_URL }}
            method: 'POST'
      - name: Deploy app production server
        if: env.DEPLOY_PROD_URL != '' && github.ref == 'refs/heads/master'
        uses: fjogeleit/http-request-action@master
        with:
            url: ${{ env.DEPLOY_PROD_URL }}
            method: 'POST'
