name: Laravel

on:
  workflow_call:
    secrets: inherit

jobs:
  php-cs-fixer:
    name: PHP-CS-Fixer
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        ref: ${{ github.head_ref }}
    - name: Update Rules
      uses: wei/wget@v1
      with:
        args: -O .php-cs-fixer.php https://raw.githubusercontent.com/SIDESO/.github/master/laravel-php-cs-fixer.php
    - name: PHP-CS-Fixer
      uses: docker://oskarstark/php-cs-fixer-ga
      with:
        args: --config=.php-cs-fixer.php
    - uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: Apply php-cs-fixer changes
        commit_user_name: SIDESO Bot # defaults to "github-actions[bot]"
        commit_user_email: my-github-actions-bot@sideso.com.co # defaults to "github-actions[bot]@users.noreply.github.com"

  laravel-tests:
    needs: php-cs-fixer
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Setup PHP with PECL extension
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.1'
    - name: Copy .env
      run: php -r "file_exists('.env') || copy('.env.example', '.env');"
    - name: Install Dependencies
      run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
    - name: Generate key
      run: php artisan key:generate
    - name: Passport Key  
      run: php artisan passport:keys
    - name: Directory Permissions
      run: chmod -R 777 storage bootstrap/cache
    - name: Create Database
      run: |
        mkdir -p database
        touch database/database.sqlite
    - name: Execute tests (Unit and Feature tests) via PHPUnit
      env:
        DB_CONNECTION: sqlite
        DB_DATABASE: database/database.sqlite
      run: php artisan test --coverage --min=80

  deployment-staging: 
    runs-on: ubuntu-latest
    needs: laravel-tests
    env:
      DEPLOY_URL: ${{ secrets.FORGE_DEPLOY_STAGING }}
    if: github.ref == 'refs/heads/stage'
    steps:
      - name: Deploy app staging server
        if: "${{ env.DEPLOY_URL != '' }}"
        uses: fjogeleit/http-request-action@master
        with:
            url: ${{ env.DEPLOY_URL }}
            method: 'POST'

  deployment-production: 
    runs-on: ubuntu-latest
    needs: laravel-tests
    env:
      DEPLOY_URL: ${{ secrets.FORGE_DEPLOY_PRODUCTION }}
    if: github.ref == 'refs/heads/master'
    steps:
      - name: Deploy app production server
        if: "${{ env.DEPLOY_URL != '' }}"
        uses: fjogeleit/http-request-action@master
        with:
            url: ${{ env.DEPLOY_URL }}
            method: 'POST'
